#!/bin/bash

DEFAULT_IMAGE="hcpsilva/starvz:latest"

IMAGE=$DEFAULT_IMAGE
PATH=`pwd`

function usage()
{
    echo "$0 [OPTIONS] <DIRECTORY>"
    echo "    where <DIRECTORY> is the *full path* to the directory containing the fxt traces"
    echo " ---"
    echo "[OPTIONS] can be any of the following, in no particular order:"
    echo "  --image=IMAGE_NAME:TAG"
    echo "    use an image instead of the default $DEFAULT_IMAGE"
}

for i in "$@"; do
    case $i in
        --image=*)
            IMAGE="${i#*=}"
            shift
            ;;
        *)
            PATH="$i"
            ;;
    esac
done

if [ ! -d "$PATH" ]; then
    echo "Given parameter is not a directory."
    echo "Please refer to the following usage example:"
    echo
    usage

    exit
fi

if [ -z $(docker images -q "$IMAGE") ] && [ "$IMAGE" == "$DEFAULT_IMAGE" ]; then
    echo "--> Image not found, pulling from repository..."
    docker pull "$IMAGE"
elif [ -z $(docker images -q "$IMAGE") ]; then
    echo "--> Image not found, be sure that your image exists..."

    exit
fi

docker run -dit \
       --name=trace_analysis \
       --mount type=bind,source=$PATH,target=/scratch \
       $IMAGE bash > /dev/null 2>&1

docker exec \
       --workdir / \
       trace_analysis \
       phase1-workflow.sh /scratch application
# I actually don't know why there is an application parameter but since it asks
# for something I might as well put something

docker container stop trace_analysis > /dev/null 2>&1

docker container rm trace_analysis > /dev/null 2>&1
